# Generated by Django 6.1.2 on 2026-10-10 19:39

import django.db.models.deletion
from django.db import migrations, models


def remap_owners_to_seller_profiles(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    SellerProfile = apps.get_model('accounts', 'SellerProfile')

    for store in Store.objects.all().iterator():
        seller = SellerProfile.objects.filter(
            user_id=store.owner_id
        ).first()

        if seller is None:
            seller = SellerProfile.objects.create(
                user_id=store.owner_id
            )

        if seller.pk != store.owner_id:
            Store.objects.filter(pk=store.pk).update(
                owner_id=seller.pk
            )


def remap_owners_back_to_users(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    SellerProfile = apps.get_model('accounts', 'SellerProfile')

    seller_users = dict(
        SellerProfile.objects.values_list('id', 'user_id')
    )

    for store in Store.objects.all().iterator():
        user_id = seller_users.get(store.owner_id)

        if user_id is not None and user_id != store.owner_id:
            Store.objects.filter(pk=store.pk).update(
                owner_id=user_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            remap_owners_to_seller_profiles,
            remap_owners_back_to_users,
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.sellerprofile'),
        ),
    ]
