# Generated by Django 6.1.2 on 2026-10-10 19:40

import django.db.models.deletion
from django.db import migrations, models


def remap_customers_to_profiles(apps, schema_editor):
    CustomerProfile = apps.get_model('accounts', 'CustomerProfile')
    CartItem = apps.get_model('orders', 'CartItem')
    Order = apps.get_model('orders', 'Order')

    user_to_profile = dict(
        CustomerProfile.objects.values_list('user_id', 'id')
    )

    for model in (CartItem, Order):
        for row in model.objects.all().iterator():
            profile_id = user_to_profile.get(row.customer_id)

            if profile_id is not None and profile_id != row.customer_id:
                model.objects.filter(pk=row.pk).update(
                    customer_id=profile_id
                )


def remap_customers_back_to_users(apps, schema_editor):
    CustomerProfile = apps.get_model('accounts', 'CustomerProfile')
    CartItem = apps.get_model('orders', 'CartItem')
    Order = apps.get_model('orders', 'Order')

    profile_to_user = dict(
        CustomerProfile.objects.values_list('id', 'user_id')
    )

    for model in (CartItem, Order):
        for row in model.objects.all().iterator():
            user_id = profile_to_user.get(row.customer_id)

            if user_id is not None and user_id != row.customer_id:
                model.objects.filter(pk=row.pk).update(
                    customer_id=user_id
                )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile'),
        ),
        migrations.RunPython(
            remap_customers_to_profiles,
            remap_customers_back_to_users,
        ),
    ]
