# Generated by Django 6.1.2 on 2026-10-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cartitem_customer_alter_order_customer'),
        ('stores', '0003_category_alter_product_options_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.product'),
        ),
    ]
